# Generated by Django 5.1.1 on 2025-07-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_is_available_book_unavailable_until'),
        ('books', '0004_auto_20150502_0953'),
    ]

    operations = [
    ]
