# Generated by Django 5.1.1 on 2025-07-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_merge_20250710_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(default='', max_length=100),
        ),
    ]
