# Generated by Django 5.1.1 on 2025-07-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
