# Generated by Django 5.1.1 on 2025-07-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookrequests', '0002_bookrequest_due_date'),
        ('bookrequests', '0003_auto_20150419_1843'),
    ]

    operations = [
    ]
